language: minimal

services:
  - docker

git:
  submodules: false

stages:
  - build quip-base
  - build quip-gap
  - build quip

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

jobs:
  include:
    - stage: build quip-base-py3
      script:
        - docker build -t libatomsquip/quip-base-py3:latest python3/quip-base
      deploy:
        provider: script
        script: docker push libatomsquip/quip-base-py3:latest
        on:
          branch: init_py3

    - stage: build quip-gap-py3
      script:
        - git clone --depth 1 https://${GITHUB_TOKEN}@github.com/libAtoms/GAP.git python3/quip-gap/GAP
        - docker build -t libatomsquip/quip-gap-py3:latest python3/quip-gap
      deploy:
        provider: script
        script: docker push libatomsquip/quip-gap-py3:latest
        on:
          branch: init_py3

    - stage: build quip-py3
      script:
        - docker build -t libatomsquip/quip-py3:latest python3/quip
      deploy:
        provider: script
        script: docker push libatomsquip/quip-py3:latest
        on:
          branch: init_py3

