language: minimal

services:
  - docker

stages:
  - build quip-base
  - build quip-gap
  - build quip

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

jobs:
  include:
    - stage: build quip-base
      script:
        - docker build -t libatomsquip/quip-base:latest quip-base
      deploy:
        provider: script
        script: docker push libatomsquip/quip-base:latest
        on:
          branch: master

    - stage: build quip-gap
      before_script:
        - echo $github_deploy_key | base64 -d > ~/.ssh/github_deploy_key
        - chmod 0600  ~/.ssh/github_deploy_key
        - eval $(ssh-agent -s)
        - ssh-add ~/.ssh/github_deploy_key
        - git clone --depth 1 git@github.com:libAtoms/GAP.git quip-gap/GAP
      script:
        - docker build -t libatomsquip/quip-gap:latest quip-gap
      deploy:
        provider: script
        script: docker push libatomsquip/quip-gap:latest
        on:
          branch: master

    - stage: build quip
      script:
        - docker build -t libatomsquip/quip:latest quip
      deploy:
        provider: script
        script: docker push libatomsquip/quip:latest
        on:
          branch: master
