language: minimal

services:
  - docker

jobs:
  include:
    - stage: build quip-base
      before_install:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker pull libatomsquip/quip-dummy-py2
      script:
        - docker build -t libatomsquip/quip-dummy-py2:latest quip-dummy-py2
      deploy:
        provider: script
        script: docker push libatomsquip/quip-dummy-py2:latest
        on:
          branch: master
