language: minimal

services:
  - docker

git:
  submodules: false

stages:
  - build quip-base
  - build quip-gap
  - build quip

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

jobs:
  include:
    - stage: build quip-base
      script:
        - docker build -t libatomsquip/quip-base-py2:latest python2/quip-base
      deploy:
        provider: script
        script: docker push libatomsquip/quip-base-py2:latest
        on:
          branch: master

    - stage: build quip-gap
      script:
        - docker build -t libatomsquip/quip-gap-py2:latest --build-arg GITHUB_TOKEN=$GITHUB_TOKEN python2/quip-gap
      deploy:
        provider: script
        script: docker push libatomsquip/quip-gap-py2:latest
        on:
          branch: master

    - stage: build quip
      script:
        - docker build -t libatomsquip/quip-py2:latest python2/quip
      deploy:
        provider: script
        script: docker push libatomsquip/quip-py2:latest
        on:
          branch: master
