language: minimal

services:
  - docker

git:
  submodules: false

jobs:
  include:
    - stage: build quip-dummy
      before_install:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker pull libatomsquip/quip-dummy-py2 || true
      script:
        - cd python2
        - docker build -t libatomsquip/quip-dummy-py2:latest quip-dummy-py2
      deploy:
        provider: script
        script: docker push libatomsquip/quip-dummy-py2:latest
        on:
          branch: master
