language: minimal

services:
  - docker

git:
  submodules: false

stages:
  - build quip-base
  - build quip-gap
  - build quip

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

jobs:
  include:
    - stage: build quip-base
      script:
        - docker build -t libatomsquip/quip-base:latest python2/quip-base
      deploy:
        provider: script
        script: docker push libatomsquip/quip-base:latest
        on:
          branch: master

    - stage: build quip-gap
      script:
        - git clone --depth 1 https://${GITHUB_TOKEN}@github.com/libAtoms/GAP.git python2/quip-gap/GAP
        - docker build -t libatomsquip/quip-gap:latest python2/quip-gap
      deploy:
        provider: script
        script: docker push libatomsquip/quip-gap:latest
        on:
          branch: master

    - stage: build quip
      script:
        - docker build -t libatomsquip/quip:latest python2/quip
      deploy:
        provider: script
        script: docker push libatomsquip/quip:latest
        on:
          branch: master
