name: Build quip-minimal Image

on: [ push ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build --tag libatomsquip/quip-minimal:latest quip-minimal

